[package]
name = "memfd_create-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.147"
reqwest = {version = "0.11.18", features = ["blocking"]}