[package]
name = "obfuscate_shellcode-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libaes = "0.7.0"
itertools = "0.13.0"
